In [1]:
import torch
import  pandas as pd
import matplotlib.pyplot as plt
print(torch.cuda.is_available())

True


In [2]:
random = torch.randn(5, 5,1)

In [3]:
random

tensor([[[ 0.5674],
         [ 0.3844],
         [-0.3160],
         [ 1.6396],
         [ 0.6234]],

        [[ 1.2791],
         [-0.5104],
         [ 0.7304],
         [-0.3966],
         [ 0.0413]],

        [[ 1.9532],
         [-0.6812],
         [ 1.1339],
         [-0.6450],
         [-1.4458]],

        [[-0.1086],
         [ 1.1622],
         [-0.7165],
         [-0.6686],
         [-0.4546]],

        [[ 0.6593],
         [-2.6193],
         [-0.2956],
         [ 1.3827],
         [-0.6522]]])

In [4]:
random.ndim

3

In [5]:
random_image = torch.rand(size=(224,224,3))

In [6]:
random_image.shape, random_image.ndim

(torch.Size([224, 224, 3]), 3)

In [7]:
r = random_image.cuda()

In [8]:
del r
torch.cuda.empty_cache()

In [9]:
torch.ones(size=(5,5))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [10]:
t = torch.arange(0,10,2)

In [11]:
z = torch.zeros_like(t)

In [12]:
z

tensor([0, 0, 0, 0, 0])

In [13]:
z.device

device(type='cpu')

In [14]:
tensor = torch.tensor([0,10,2])
# tensor = tensor.cuda()
tensor

tensor([ 0, 10,  2])

In [15]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 519 μs, sys: 129 μs, total: 648 μs
Wall time: 386 μs


tensor(104)

In [16]:
tensor @ tensor

tensor(104)

In [17]:
torch.mm(torch.rand(3,5),torch.rand(5,1))

tensor([[0.2112],
        [0.4718],
        [0.5876]])

In [18]:
t = torch.rand(3,5)

In [19]:
t

tensor([[0.1803, 0.1270, 0.5182, 0.5822, 0.3764],
        [0.5526, 0.9646, 0.7954, 0.9141, 0.1426],
        [0.3639, 0.4766, 0.1828, 0.4028, 0.0022]])

In [20]:
t.T

tensor([[0.1803, 0.5526, 0.3639],
        [0.1270, 0.9646, 0.4766],
        [0.5182, 0.7954, 0.1828],
        [0.5822, 0.9141, 0.4028],
        [0.3764, 0.1426, 0.0022]])

In [21]:
a = torch.arange(0,100,10)

In [22]:
%%time
a.type(torch.float32).mean()

CPU times: user 800 μs, sys: 185 μs, total: 985 μs
Wall time: 600 μs


tensor(45.)

In [23]:
%%time
a.sum()


CPU times: user 0 ns, sys: 1.5 ms, total: 1.5 ms
Wall time: 814 μs


tensor(450)

In [24]:
a.argmin()

tensor(0)

In [25]:
x = torch.arange(1,100,10)

In [26]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [27]:
x = x.reshape(5,2)

In [28]:
z = x.view(5,2)

In [29]:
z[:,0] = 5

In [30]:
z

tensor([[ 5, 11],
        [ 5, 31],
        [ 5, 51],
        [ 5, 71],
        [ 5, 91]])

In [31]:
x

tensor([[ 5, 11],
        [ 5, 31],
        [ 5, 51],
        [ 5, 71],
        [ 5, 91]])

In [32]:
stacd = torch.stack([x,x,x,x,x,x])

In [33]:
stacd

tensor([[[ 5, 11],
         [ 5, 31],
         [ 5, 51],
         [ 5, 71],
         [ 5, 91]],

        [[ 5, 11],
         [ 5, 31],
         [ 5, 51],
         [ 5, 71],
         [ 5, 91]],

        [[ 5, 11],
         [ 5, 31],
         [ 5, 51],
         [ 5, 71],
         [ 5, 91]],

        [[ 5, 11],
         [ 5, 31],
         [ 5, 51],
         [ 5, 71],
         [ 5, 91]],

        [[ 5, 11],
         [ 5, 31],
         [ 5, 51],
         [ 5, 71],
         [ 5, 91]],

        [[ 5, 11],
         [ 5, 31],
         [ 5, 51],
         [ 5, 71],
         [ 5, 91]]])

In [34]:
x = x.reshape(10,1)
x.shape

torch.Size([10, 1])

In [35]:
te = x.squeeze()

In [36]:
te

tensor([ 5, 11,  5, 31,  5, 51,  5, 71,  5, 91])

In [37]:
te.shape

torch.Size([10])

In [38]:
te.unsqueeze(dim=1)

tensor([[ 5],
        [11],
        [ 5],
        [31],
        [ 5],
        [51],
        [ 5],
        [71],
        [ 5],
        [91]])

In [39]:
x = torch.randn(224,224,3)
x.size()

torch.Size([224, 224, 3])

In [40]:
per = x.permute(2,0,1)

In [41]:
per.shape

torch.Size([3, 224, 224])

In [42]:
x[0,0,0] = 728218

In [43]:
x[0,0,0]

tensor(728218.)

In [44]:
per = x.permute(2,0,1)

In [45]:
per[0,0,0]

tensor(728218.)

In [46]:
new = torch.arange(1,10).reshape(1,3,3)

In [47]:
new

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [48]:
new[0,0]

tensor([1, 2, 3])

In [49]:
new[0][2][2]

tensor(9)

In [50]:
new[:,:,2]

tensor([[3, 6, 9]])

In [51]:
torch.manual_seed(42)
torch.rand(3,4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [52]:
torch.manual_seed(42)
torch.rand(3,4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [53]:
torch.cuda.device_count()

1

In [54]:
new.device

device(type='cpu')

In [68]:
t = torch.tensor([1,2,3,4,5])

In [69]:
t

tensor([1, 2, 3, 4, 5])

In [70]:
t.device

device(type='cpu')

In [71]:
%%time
t= t.to('cuda')

CPU times: user 1.71 ms, sys: 18.1 ms, total: 19.8 ms
Wall time: 18.4 ms


In [72]:
%%time
t.cuda()

CPU times: user 50 μs, sys: 0 ns, total: 50 μs
Wall time: 57.9 μs


tensor([1, 2, 3, 4, 5], device='cuda:0')

In [73]:
t.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [74]:
t = t.cpu().numpy()
t

array([1, 2, 3, 4, 5])

In [125]:
# torch.manual_seed(42)
t = torch.rand(1,7)

In [129]:
torch.matmul(torch.rand(7,7),torch.rand(1,7).T)

tensor([[1.7425],
        [1.5797],
        [1.2682],
        [0.7689],
        [1.5170],
        [1.0868],
        [0.9026]])

In [141]:
torch.manual_seed(1234)
a = (torch.rand(2,3)).to("cuda")

In [142]:
b = (torch.rand(2,3)).to("cuda")

In [143]:
a,b

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [145]:
c =torch.matmul(a,b.T)

In [147]:
print(c)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')


In [149]:
a = torch.rand(1, 1, 1, 10)

In [152]:
a.size()

torch.Size([1, 1, 1, 10])

In [154]:
a.squeeze().size()

torch.Size([10])